<?php
/**
 * Thelema
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Thelema Commercial License
 * that is bundled with this package in the file LICENSE.txt.
 *
 * @category    Thelema
 * @package     Thelema_HoneyPot
 * @copyright   Copyright (c) 2013-2017 HoneyPot (http://www.thelema-ict.com)
 * @author      Lorenzo Ricci <lricci@thelema-ict.com>
 * @license     http://www.thelema-ict.com/commercial-license-agreement  Thelema Commercial License
 */

?>
<input name="<?php echo Mage::getSingleton('thelema_honeypot/pot')->getFormHoney() ?>" type="hidden" value="" class="input-text honeypot"/>